services:
  - type: web
    name: berryboy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: berryboy-db
          property: connectionString

databases:
  - name: berryboy-db
    databaseName: berryboy
    user: berryboy
    plan: free
